version: "3.8"

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - reddit

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"

  reddit:
    build:
      context: ./reddit
      dockerfile: Dockerfile.reddit
    container_name: reddit
    ports:
      - "8001:8000"